# Generated by Django 5.2.8 on 2025-12-09 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_management', '0004_alter_draftlearninggoal_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(default=0)),
                ('question', models.TextField(default='')),
                ('answer', models.TextField(blank=True)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exam Log',
                'verbose_name_plural': 'Exam Logs',
            },
        ),
        migrations.CreateModel(
            name='ExamEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('feedback', models.TextField(default='')),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='exam.examlog')),
            ],
            options={
                'verbose_name': 'Exam Evaluation',
                'verbose_name_plural': 'Exam Evaluations',
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('mcq', 'MCQ'), ('wt', 'WT'), ('ct', 'CT')], max_length=10)),
                ('attempt_number', models.PositiveIntegerField(default=0)),
                ('current_question_number', models.PositiveIntegerField(default=0)),
                ('max_questions', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True, default='')),
                ('used_tokens', models.PositiveBigIntegerField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='task_management.learninggoal')),
                ('main_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='task_management.learningmaintopic')),
                ('sub_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='task_management.learningsubtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Session',
                'verbose_name_plural': 'Exam Sessions',
            },
        ),
        migrations.AddField(
            model_name='examlog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='exam.examsession'),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(condition=models.Q(('format', 'ct'), ('learning_goal__isnull', False)), fields=('user', 'learning_goal', 'attempt_number'), name='unique_ct_attempt_per_goal'),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(condition=models.Q(('format', 'mcq'), ('main_topic__isnull', False)), fields=('user', 'main_topic', 'attempt_number'), name='unique_mcq_attempt_per_main_topic'),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(condition=models.Q(('format', 'wt'), ('main_topic__isnull', False)), fields=('user', 'main_topic', 'attempt_number'), name='unique_wt_attempt_per_main_topic'),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(condition=models.Q(('format', 'mcq'), ('sub_topic__isnull', False)), fields=('user', 'sub_topic', 'attempt_number'), name='unique_mcq_attempt_per_sub_topic'),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(condition=models.Q(('format', 'wt'), ('sub_topic__isnull', False)), fields=('user', 'sub_topic', 'attempt_number'), name='unique_wt_attempt_per_sub_topic'),
        ),
        migrations.AddConstraint(
            model_name='examlog',
            constraint=models.UniqueConstraint(fields=('session', 'question_number'), name='unique_session-question_number'),
        ),
    ]
