# Generated by Django 5.2.8 on 2026-01-30 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0)),
                ('max_score', models.FloatField(default=0)),
                ('accuracy_rate', models.FloatField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('used_tokens', models.PositiveBigIntegerField(default=0)),
                ('report', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exam Result',
                'verbose_name_plural': 'Exam Results',
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('target_level', models.CharField(choices=[('goal', 'Learning Goal'), ('main_topic', 'Main Topic'), ('sub_topic', 'Sub Topic')], max_length=20)),
                ('flow_type', models.CharField(choices=[('per_question', 'Per Question'), ('batch', 'Batch Evaluation')], max_length=20)),
                ('scoring_method', models.CharField(choices=[('binary', 'Binary (Correct/Incorrect)'), ('rubric', 'Rubric Based'), ('rubric_heavy', 'Advanced Rubric')], max_length=20)),
                ('default_questions', models.PositiveIntegerField()),
                ('max_score_per_question', models.PositiveIntegerField()),
                ('allow_post_chat', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='examsession',
            name='unique_ct_attempt_per_goal',
        ),
        migrations.RemoveConstraint(
            model_name='examsession',
            name='unique_mcq_attempt_per_main_topic',
        ),
        migrations.RemoveConstraint(
            model_name='examsession',
            name='unique_wt_attempt_per_main_topic',
        ),
        migrations.RemoveConstraint(
            model_name='examsession',
            name='unique_mcq_attempt_per_sub_topic',
        ),
        migrations.RemoveConstraint(
            model_name='examsession',
            name='unique_wt_attempt_per_sub_topic',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='format',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='used_tokens',
        ),
        migrations.AddField(
            model_name='examresult',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='exam.examsession'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='exam_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='exam_sessions', to='exam.examtype'),
            preserve_default=False,
        ),
    ]
