# Generated by Django 5.2.8 on 2026-02-06 05:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_examresult_examtype_and_more'),
        ('task_management', '0005_remove_learningsubtopic_learning_goal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exam Answer',
                'verbose_name_plural': 'Exam Answers',
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('generated', 'Generated'), ('answered', 'Answered'), ('evaluated', 'Evaluated'), ('skipped', 'Skipped')], default='initialized', max_length=20)),
                ('question_number', models.PositiveIntegerField(default=0)),
                ('question', models.TextField()),
                ('max_score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exam Question',
                'verbose_name_plural': 'Exam Questions',
            },
        ),
        migrations.CreateModel(
            name='ExamSessionSlice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Exam Session Slice',
                'verbose_name_plural': 'Exam Session Slices',
            },
        ),
        migrations.RemoveField(
            model_name='examlog',
            name='session',
        ),
        migrations.RemoveField(
            model_name='examevaluation',
            name='exam_log',
        ),
        migrations.AddField(
            model_name='examsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('evaluating', 'Evaluating'), ('finished', 'Finished'), ('aborted', 'Aborted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='examevaluation',
            name='feedback',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='examevaluation',
            name='score',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='attempt_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='learning_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.learninggoal'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='main_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.learningmaintopic'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='sub_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.learningsubtopic'),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['created_at'], name='exam_examre_created_24287c_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['user', 'learning_goal', 'exam_type'], name='exam_examse_user_id_642692_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['user', 'main_topic', 'exam_type'], name='exam_examse_user_id_0b9df4_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['user', 'sub_topic', 'exam_type'], name='exam_examse_user_id_5632ba_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['user', 'created_at'], name='exam_examse_user_id_fa101d_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['exam_type', 'created_at'], name='exam_examse_exam_ty_0dd60a_idx'),
        ),
        migrations.AddIndex(
            model_name='examtype',
            index=models.Index(fields=['is_active'], name='exam_examty_is_acti_fd2086_idx'),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('learning_goal__isnull', False), ('main_topic__isnull', True), ('sub_topic__isnull', True)), models.Q(('learning_goal__isnull', True), ('main_topic__isnull', False), ('sub_topic__isnull', True)), models.Q(('learning_goal__isnull', True), ('main_topic__isnull', True), ('sub_topic__isnull', False)), _connector='OR'), name='only_one_exam_target_set'),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(condition=models.Q(('learning_goal__isnull', False)), fields=('user', 'learning_goal', 'exam_type', 'attempt_number'), name='unique_user-goal_attempt'),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(condition=models.Q(('main_topic__isnull', False)), fields=('user', 'main_topic', 'exam_type', 'attempt_number'), name='unique_user-main_topic_attempt'),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(condition=models.Q(('sub_topic__isnull', False)), fields=('user', 'sub_topic', 'exam_type', 'attempt_number'), name='unique_user-sub_topic_attempt'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.examsession'),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='exam.examquestion'),
        ),
        migrations.AddField(
            model_name='examevaluation',
            name='question',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='exam.examquestion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examsessionslice',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slices', to='exam.examsession'),
        ),
        migrations.DeleteModel(
            name='ExamLog',
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['session'], name='exam_examqu_session_be7d48_idx'),
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['session', 'question_number'], name='exam_examqu_session_be3167_idx'),
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['status'], name='exam_examqu_status_73b649_idx'),
        ),
        migrations.AddConstraint(
            model_name='examquestion',
            constraint=models.UniqueConstraint(fields=('session', 'question_number'), name='unique_session-question_number'),
        ),
        migrations.AddIndex(
            model_name='examsessionslice',
            index=models.Index(fields=['session'], name='exam_examse_session_29e7e5_idx'),
        ),
        migrations.AddIndex(
            model_name='examsessionslice',
            index=models.Index(fields=['started_at'], name='exam_examse_started_68d96f_idx'),
        ),
        migrations.AddConstraint(
            model_name='examsessionslice',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('session',), name='exam_session_one_open_slice_open_only'),
        ),
    ]
