# Generated by Django 5.2.8 on 2026-02-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_examanswer_examquestion_examsessionslice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examevaluation',
            name='detail_scores',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
