# Generated by Django 5.2.8 on 2026-02-11 06:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_examevaluation_detail_scores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examquestion',
            options={'get_latest_by': 'created_at', 'verbose_name': 'Exam Question', 'verbose_name_plural': 'Exam Questions'},
        ),
        migrations.AlterField(
            model_name='examevaluation',
            name='score',
            field=models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='accuracy_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examresult',
            name='max_score',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='total_score',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
