# Generated by Django 5.2.8 on 2026-02-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_examquestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='choices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='examevaluation',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
