# Generated by Django 5.2.8 on 2026-02-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_examquestion_choices_examquestion_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examevaluation',
            name='rubric_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='rubric_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
