# Generated by Django 5.2.8 on 2025-12-09 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_management', '0004_alter_draftlearninggoal_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_count', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('total_count', models.PositiveBigIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('sub_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_sessions', to='task_management.learningsubtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LectureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ai', 'AI'), ('user', 'USER'), ('master', 'MASTER')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='lecture.lecturesession')),
            ],
        ),
    ]
