# Generated by Django 5.2.8 on 2026-01-01 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_management', '0004_alter_draftlearninggoal_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_number', models.PositiveIntegerField()),
                ('summary', models.TextField(blank=True)),
                ('total_tokens', models.PositiveBigIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('sub_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_sessions', to='task_management.learningsubtopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lecture Session',
                'verbose_name_plural': 'Lecture Sessions',
                'ordering': ['lecture_number'],
            },
        ),
        migrations.CreateModel(
            name='LectureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ai', 'AI'), ('user', 'USER'), ('system', 'SYSTEM')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='lecture.lecturesession')),
            ],
        ),
        migrations.CreateModel(
            name='LectureTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('sub_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_topics', to='task_management.learningsubtopic')),
            ],
            options={
                'verbose_name': 'Lecture Topic',
                'verbose_name_plural': 'Lecture Topics',
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='lecturesession',
            constraint=models.UniqueConstraint(fields=('user', 'sub_topic', 'lecture_number'), name='unique_lecture_number_per_topic'),
        ),
        migrations.AddConstraint(
            model_name='lecturetopic',
            constraint=models.UniqueConstraint(fields=('sub_topic', 'order'), name='unique_topic_order_per_sub_topic'),
        ),
    ]
