# Generated by Django 5.2.8 on 2025-12-23 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
        ('task_management', '0004_alter_draftlearninggoal_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Lecture Topic',
                'verbose_name_plural': 'Lecture Topics',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='lecturesession',
            options={'ordering': ['lecture_number'], 'verbose_name': 'Lecture Session', 'verbose_name_plural': 'Lecture Sessions'},
        ),
        migrations.RenameField(
            model_name='lecturesession',
            old_name='total_count',
            new_name='total_tokens',
        ),
        migrations.RemoveField(
            model_name='lecturesession',
            name='lecture_count',
        ),
        migrations.AddField(
            model_name='lecturesession',
            name='lecture_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecturelog',
            name='role',
            field=models.CharField(choices=[('ai', 'AI'), ('user', 'USER'), ('system', 'SYSTEM')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='lecturesession',
            constraint=models.UniqueConstraint(fields=('user', 'sub_topic', 'lecture_number'), name='unique_lecture_number_per_topic'),
        ),
        migrations.AddField(
            model_name='lecturetopic',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='lecture.lecturesession'),
        ),
        migrations.AddConstraint(
            model_name='lecturetopic',
            constraint=models.UniqueConstraint(fields=('session', 'order'), name='unique_topic_order_per_session'),
        ),
    ]
