# Generated by Django 5.2.8 on 2026-01-02 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
        ('task_management', '0004_alter_draftlearninggoal_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lecture Progress',
                'verbose_name_plural': 'Lecture Progress Records',
            },
        ),
        migrations.AlterModelOptions(
            name='lecturesession',
            options={'ordering': ['user', 'sub_topic', 'lecture_number'], 'verbose_name': 'Lecture Session', 'verbose_name_plural': 'Lecture Sessions'},
        ),
        migrations.AlterModelOptions(
            name='lecturetopic',
            options={'ordering': ['default_order'], 'verbose_name': 'Lecture Topic', 'verbose_name_plural': 'Lecture Topics'},
        ),
        migrations.RemoveConstraint(
            model_name='lecturetopic',
            name='unique_topic_order_per_sub_topic',
        ),
        migrations.RenameField(
            model_name='lecturetopic',
            old_name='order',
            new_name='default_order',
        ),
        migrations.RemoveField(
            model_name='lecturetopic',
            name='is_completed',
        ),
        migrations.AddConstraint(
            model_name='lecturetopic',
            constraint=models.UniqueConstraint(fields=('sub_topic', 'default_order'), name='unique_topic_default_order_per_sub_topic'),
        ),
        migrations.AddField(
            model_name='lectureprogress',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='lecture.lecturesession'),
        ),
        migrations.AddField(
            model_name='lectureprogress',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='lecture.lecturetopic'),
        ),
        migrations.AddField(
            model_name='lecturesession',
            name='topics',
            field=models.ManyToManyField(related_name='lecture_sessions', through='lecture.LectureProgress', to='lecture.lecturetopic'),
        ),
        migrations.AddConstraint(
            model_name='lectureprogress',
            constraint=models.UniqueConstraint(fields=('session', 'topic'), name='unique_progress_per_session_and_topic'),
        ),
    ]
