# Generated by Django 5.2.8 on 2026-01-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_lectureprogress_alter_lecturesession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturesession',
            name='can_continue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lecturesession',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturesession',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lecturesession',
            name='report',
            field=models.TextField(blank=True),
        ),
    ]
