# Generated by Django 5.2.8 on 2026-01-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_lecturesession_can_continue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturesession',
            name='last_report_log_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
