# Generated by Django 5.2.8 on 2026-01-27 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_lecturesession_last_report_log_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturesession',
            name='ended',
        ),
        migrations.RemoveField(
            model_name='lecturesession',
            name='started_at',
        ),
        migrations.CreateModel(
            name='LectureSessionSlice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slices', to='lecture.lecturesession')),
            ],
            options={
                'verbose_name': 'Lecture Session Slice',
                'verbose_name_plural': 'Lecture Session Slices',
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('session',), name='one_open_slice_per_session')],
            },
        ),
    ]
