# Generated by Django 5.2.8 on 2026-01-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_remove_lecturesession_ended_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturesession',
            old_name='total_tokens',
            new_name='used_tokens',
        ),
    ]
