# Generated by Django 5.2.8 on 2026-02-06 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0006_rename_total_tokens_lecturesession_used_tokens'),
        ('task_management', '0005_remove_learningsubtopic_learning_goal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturesession',
            options={'ordering': ['lecture_number'], 'verbose_name': 'Lecture Session', 'verbose_name_plural': 'Lecture Sessions'},
        ),
        migrations.RemoveConstraint(
            model_name='lecturesessionslice',
            name='one_open_slice_per_session',
        ),
        migrations.RemoveField(
            model_name='lectureprogress',
            name='order',
        ),
        migrations.AddIndex(
            model_name='lecturelog',
            index=models.Index(fields=['session', 'created_at'], name='lecture_lec_session_f24743_idx'),
        ),
        migrations.AddIndex(
            model_name='lectureprogress',
            index=models.Index(fields=['session', 'is_completed'], name='lecture_lec_session_e65e23_idx'),
        ),
        migrations.AddIndex(
            model_name='lectureprogress',
            index=models.Index(fields=['topic'], name='lecture_lec_topic_i_481359_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturesession',
            index=models.Index(fields=['user', 'sub_topic'], name='lecture_lec_user_id_ae607a_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturesession',
            index=models.Index(fields=['user'], name='lecture_lec_user_id_c551fd_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturesession',
            index=models.Index(fields=['is_finished'], name='lecture_lec_is_fini_9910fd_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturesession',
            index=models.Index(fields=['can_continue'], name='lecture_lec_can_con_733aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturesessionslice',
            index=models.Index(fields=['session', 'ended_at'], name='lecture_lec_session_67a3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturesessionslice',
            index=models.Index(fields=['started_at'], name='lecture_lec_started_ce7be1_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturetopic',
            index=models.Index(fields=['sub_topic'], name='lecture_lec_sub_top_fee426_idx'),
        ),
        migrations.AddConstraint(
            model_name='lecturesessionslice',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('session',), name='lecture_session_one_open_slice_open_only'),
        ),
    ]
