# Generated by Django 5.2.8 on 2025-11-30 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_global', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='DraftLearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('current_level', models.TextField(blank=True)),
                ('target_level', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('raw_generated_data', models.JSONField(blank=True, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_learning_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Draft Learning Goal',
                'verbose_name_plural': 'Draft Learning Goals',
            },
        ),
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('current_level', models.TextField(blank=True)),
                ('target_level', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to='task_management.category')),
                ('draft', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_learning_goal', to='task_management.draftlearninggoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Goal',
                'verbose_name_plural': 'Learning Goals',
            },
        ),
        migrations.CreateModel(
            name='LearningMainTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_topics', to='task_management.learninggoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_main_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Main Topic',
                'verbose_name_plural': 'Learning Main Topics',
            },
        ),
        migrations.CreateModel(
            name='LearningSubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_topics', to='task_management.learninggoal')),
                ('main_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_topics', to='task_management.learningmaintopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sub_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning Sub Topic',
                'verbose_name_plural': 'Learning Sub Topics',
            },
        ),
        migrations.CreateModel(
            name='UserInterestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_users', to='task_management.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interest_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Interest Category',
                'verbose_name_plural': 'User Interest Categories',
                'constraints': [models.UniqueConstraint(fields=('user', 'category'), name='unique_user_category')],
            },
        ),
    ]
