# Generated by Django 5.2.8 on 2025-12-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learninggoal',
            old_name='Category',
            new_name='category',
        ),
    ]
