# Generated by Django 5.2.8 on 2025-12-02 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_rename_category_learninggoal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftlearninggoal',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task_management.category'),
            preserve_default=False,
        ),
    ]
