# Generated by Django 5.2.8 on 2025-12-09 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_draftlearninggoal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftlearninggoal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_learning_goals', to='task_management.category'),
        ),
    ]
