# Generated by Django 5.2.8 on 2026-02-06 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0004_alter_draftlearninggoal_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningsubtopic',
            name='learning_goal',
        ),
        migrations.RemoveField(
            model_name='learningsubtopic',
            name='user',
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['owner'], name='task_manage_owner_i_d1b822_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_global'], name='task_manage_is_glob_88797f_idx'),
        ),
        migrations.AddIndex(
            model_name='draftlearninggoal',
            index=models.Index(fields=['user'], name='task_manage_user_id_934aff_idx'),
        ),
        migrations.AddIndex(
            model_name='draftlearninggoal',
            index=models.Index(fields=['category'], name='task_manage_categor_1a4eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='draftlearninggoal',
            index=models.Index(fields=['is_finalized'], name='task_manage_is_fina_86ec47_idx'),
        ),
        migrations.AddIndex(
            model_name='draftlearninggoal',
            index=models.Index(fields=['created_at'], name='task_manage_created_9633b7_idx'),
        ),
        migrations.AddIndex(
            model_name='learninggoal',
            index=models.Index(fields=['user'], name='task_manage_user_id_a81d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='learninggoal',
            index=models.Index(fields=['category'], name='task_manage_categor_e3a4d7_idx'),
        ),
        migrations.AddIndex(
            model_name='learninggoal',
            index=models.Index(fields=['created_at'], name='task_manage_created_9a923b_idx'),
        ),
        migrations.AddIndex(
            model_name='learningmaintopic',
            index=models.Index(fields=['user'], name='task_manage_user_id_91cd39_idx'),
        ),
        migrations.AddIndex(
            model_name='learningmaintopic',
            index=models.Index(fields=['learning_goal'], name='task_manage_learnin_f68d11_idx'),
        ),
        migrations.AddIndex(
            model_name='learningmaintopic',
            index=models.Index(fields=['status'], name='task_manage_status_c29f02_idx'),
        ),
        migrations.AddIndex(
            model_name='learningsubtopic',
            index=models.Index(fields=['main_topic'], name='task_manage_main_to_9ee3a8_idx'),
        ),
        migrations.AddIndex(
            model_name='learningsubtopic',
            index=models.Index(fields=['status'], name='task_manage_status_7f6432_idx'),
        ),
        migrations.AddIndex(
            model_name='userinterestcategory',
            index=models.Index(fields=['user'], name='task_manage_user_id_860f69_idx'),
        ),
        migrations.AddIndex(
            model_name='userinterestcategory',
            index=models.Index(fields=['category'], name='task_manage_categor_578499_idx'),
        ),
    ]
