# Generated by Django 5.2.8 on 2026-02-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0005_remove_learningsubtopic_learning_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninggoal',
            name='rubric_schema',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningmaintopic',
            name='rubric_schema',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningsubtopic',
            name='rubric_schema',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
