# Generated by Django 5.2.8 on 2026-02-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0006_learninggoal_rubric_schema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninggoal',
            name='rubric_schema',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
